### ISSUE TITLE
industrial edge docs not up to date #nodeploy

### ISSUE THREAD

**Issue by manfredmuth** [hybrid-cloud-patterns/industrial-edge#197]
Hi,

I tried to follow the documentation.
Unfortunately it is completely outdated.
The referred scripts like make_common_subtree.sh  in v2.1.1 are not available any more. And it seems they are missing in all the branches.
Can you please update the docs.

Cheers

Manfred

**Comment by claudiol** [comment]
@manfredmuth I have updated the documentation for Industrial Edge in [PR #261](https://github.com/hybrid-cloud-patterns/docs/pull/261).
If you can take a look and verify that the steps describe the installation process better please let us know.  Sorry it took us a bit to update the docs. 

You can see the new docs on our [Getting Started](https://hybrid-cloud-patterns.io/patterns/industrial-edge/getting-started/) page for Industrial Edge.

**Comment by claudiol** [comment]
Updated documentation for installation process.  Closing
