### ISSUE TITLE
industrial-edge-datacenter and industrial-edge-factory applications show "out of sync" in cluster-wide GitOps instance

### ISSUE THREAD

**Issue by mhjacks** [hybrid-cloud-patterns/industrial-edge#38]
The two applications named above show out of sync perpetually in ArgoCD.  This is because there are RoleBindings and ClusterRoleBindings that are part of the installation that are managed by the operators and are not represented in the GitOps structure.

**Comment by claudiol** [comment]
Closing.  This should be fixed
