### ISSUE TITLE
AWS S3 is required

### ISSUE THREAD

**Issue by takleung** [hybrid-cloud-patterns/industrial-edge#51]
found that # Secret used for S3 functionality in manuela-data-lake is required on values-secret.yaml. May I know it is a must as I don't have it. thank you

Ray

**Comment by claudiol** [comment]
So S3 is not required unless you want the Data Lake functionality deployed.  The team is looking at adding a boolean that will determine whether or not to deploy the S3 functionality.  We will be doing that in the next version of the Industrial Edge pattern.
