### ISSUE TITLE
Failed to deploy.

### ISSUE THREAD

**Issue by johwes** [hybrid-cloud-patterns/industrial-edge#52]
I tried to run this today.

Ordered edge demo env from RHPDS.

Cloned the repos as instructed here, 
https://github.com/hybrid-cloud-patterns/industrial-edge#start-here

But the environment doesn't get deployed correctly.
Difficult to know exactly where things go wrong, but one thing that might be relevant is that a pipelin run in manuela-ci fails,
"
PipelineRun manuela-ci/seed-run-9jr8h doesn't bind Pipeline manuela-ci/seed's Workspaces correctly: pipeline requires workspace with name "github-secret" be provided by pipelinerun

"

**Comment by ipbabble** [comment]
Comments/observations: 
Confirmed Quay repos have been created. 
values_secrets.template is all wrong. Mentions PLAINTEXT and not base64! 
Also seems to have incorrect labels. 
@ipbabble to update the values-secrets.template file and the docs to explain more clearly.

**Comment by claudiol** [comment]
This will be tested again with the new v2.1 branch in RHPDS.  You can look at https://issues.redhat.com/browse/GPTEINFRA-2961 for status.  Currently done but needs to be tested.
