### ISSUE TITLE
JupyterHub pods not running

### ISSUE THREAD

**Issue by mamurak** [hybrid-cloud-patterns/industrial-edge#54]
After deploying IE 2.0 on OCP 4.8, JupyterHub pods are not running in project `manuela-ml-workspace` as indicated in the [instructions](https://hybrid-cloud-patterns.io/industrial-edge/application/#application-ai-model-changes-with-devops).

**Comment by mamurak** [comment]
The [KfDef](https://github.com/hybrid-cloud-patterns/industrial-edge/blob/main/charts/datacenter/opendatahub/templates/odh-kfdef.yaml) file is outdated for ODH 1.1.1.
The repo references need to be updated accordingly.

**Comment by DanielFroehlich** [comment]
tried it today using RHPDS, still not working. RHPDS is not yet using the fix #55 
After manually applying the fix to that RHPDS instance, notebooks do not start. Error Message:
` forbidden: User \\"system:serviceaccount:manuela-ml-workspace:jupyterhub-hub\\" cannot list resource \\"nodes\\" in API group \\"\\" at the cluster scope","`
Brute force workaround: 
`oc adm policy add-scc-to-user cluster-admin -z jupyterhub-hub --as system:admin -n manuela-ml-workspace`

**Comment by mamurak** [comment]
I can reproduce this. It seems the ODH operator is automatically upgrading to version 1.1.2, which seems to be unstable and incompatible with our changes. If I'm right, we would need to install ODH operator with Manual upgrade policy and make sure it's on 1.1.1.
I'm off for one week, and then I'll look into it.

**Comment by mamurak** [comment]
ODH 1.1.2 is running. I've prepared PR #76 for the updated Kfdef.
You may need to delete the `jupyterhub` imagestream in project `manuela-ml-workspace` if there are image pull errors. I haven't found out where this imagestream is created in the first place.

**Comment by claudiol** [comment]
Changes merged by mjacks
