### ISSUE TITLE
Github-pull-request pipeline task fails

### ISSUE THREAD

**Issue by mamurak** [hybrid-cloud-patterns/industrial-edge#56]
After updating the sensor application and triggering the delivery pipeline using `make build-and-test`, the final pipeline run for `stage-production` fails during task `github-pull-request`. The error message reads:
```
declared workspace "github-secret" is required but has not been bound
```

Environment: OCP 4.8, deployed through RHPDS (OpenShift 4.8 Industrial Edge - Deployed).

**Comment by claudiol** [comment]
This has been fixed. The secret now lives in the Vault instance and gets applied to the namespace.  Closing.
