### ISSUE TITLE
Anomaly inference pods not running

### ISSUE THREAD

**Issue by mamurak** [hybrid-cloud-patterns/industrial-edge#59]
Vibration anomalies are not detected in the line sensor dashboard even though messaging is configured accordingly. The `anomaly-detection-predictor` pods are not running in namespace `manuela-tst-all`.

Environment: OCP 4.8, deployed through RHPDS (OpenShift 4.8 Industrial Edge - Deployed).

**Comment by mhjacks** [comment]
Thanks for the contribution!
