### ISSUE TITLE
manuela-stormshift-machine-sensor pods crash looping on RHPDS fully deployed

### ISSUE THREAD

**Issue by DanielFroehlich** [hybrid-cloud-patterns/industrial-edge#75]
I did deploy the RHPDS fully deployed demo today.
Problem Statement:
manuela line dashboard does not show data, not events being shipped to kafka. 

All pods in the manuela-stormshift-machine-sensor namespace are crash looping with error message:
`java.net.UnknownHostException: 
 broker-amq-mqtt-all-0-svc-rte-manuela-stormshift-messaging.apps.edge-kfsmk.kfsmk.sandbox230.opentlc.com
 `

Root cause: the config is wrong, the host name "...**edge**...." is incorrect, it needs to be "...**cluster**..." in the RHPDS fully deployed version.

Here is the correct hostname from the route in manuel-stormshift-messaging:
broker-amq-mqtt-all-0-svc-rte-manuela-stormshift-messaging.apps.cluster-kfsmk.kfsmk.sandbox230.opentlc.com

Workaround:
Change the ConfigMap "machine-sensor-1|" in namespace from ...edge... to ...cluster...

**Comment by DanielFroehlich** [comment]
The manuela-stormshift-line-dashboard is not showing any data. 
Same reason, it is pointing to the wrong AMQ broker url with "...edge..." instead of "...cluster...."
Please also fix manuela-stormshift-line-dashboard/line-dashboard-configmap

**Comment by claudiol** [comment]
> The manuela-stormshift-line-dashboard is not showing any data. Same reason, it is pointing to the wrong AMQ broker url with "...edge..." instead of "...cluster...." Please also fix manuela-stormshift-line-dashboard/line-dashboard-configmap

Checking on this today for you.  Thanks Daniel!

**Comment by claudiol** [comment]
@DanielFroehlich We are finding some discrepancies and we are going to look into them this afternoon (3/7/2022).  The current RHPDS deployment uses the stable-2.0 branch which uses the datacenter.clustername,

**Comment by mhjacks** [comment]
Reverted 01d3c30 and bfc00d7 from hybrid-cloud-patterns/manuela-dev, which are particular to our fork.  Validating
