### ISSUE TITLE
argocd-env handling seems not to work on main

### ISSUE THREAD

**Issue by mhjacks** [hybrid-cloud-patterns/industrial-edge#93]
```
make[2]: Leaving directory '/home/martjack/gitwork/newprints/industrial-edge'
make[1]: Leaving directory '/home/martjack/gitwork/newprints/industrial-edge'
make argosecret
make[1]: Entering directory '/home/martjack/gitwork/newprints/industrial-edge'
echo "Delegating argosecret target"
Delegating argosecret target
make -f common/Makefile argosecret
make[2]: Entering directory '/home/martjack/gitwork/newprints/industrial-edge'
PATTERN="" TARGET_NAMESPACE="" COMPONENT="" SECRET_NAME="" common/scripts/secret.sh
Checking for namespace  to exist: OK
Checking for secrets/-gitops-cluster to be populated in -: |^Cmake[2]: *** [common/Makefile:29: argosecret] Interrupt
make[1]: *** [Makefile:24: argosecret] Interrupt
make: *** [Makefile:35: install] Interrupt

martjack@martjack:~/gitwork/newprints/industrial-edge
2159db3f main % u= origin/main
% git checkout v2.1   
Switched to branch 'v2.1'
Your branch is up to date with 'upstream/v2.1'.
martjack@martjack:~/gitwork/newprints/industrial-edge
a1843c71 v2.1 % u= upstream/v2.1
% make argosecret
make -f common/Makefile \
	PATTERN=industrial-edge TARGET_NAMESPACE=manuela-ci \
	SECRET_NAME="argocd-env" COMPONENT=datacenter argosecret
make[1]: Entering directory '/home/martjack/gitwork/newprints/industrial-edge'
PATTERN="industrial-edge" TARGET_NAMESPACE="manuela-ci" COMPONENT="datacenter" SECRET_NAME="argocd-env" common/scripts/secret.sh
Checking for namespace manuela-ci to exist: OK
Checking for secrets/datacenter-gitops-cluster to be populated in industrial-edge-datacenter: OK
Conditions met, managing secret argocd-env in manuela-ci
secret/argocd-env created
make[1]: Leaving directory '/home/martjack/gitwork/newprints/industrial-edge'
```

The workaround is to checkout v2.1 and run `make argosecret`. This seems to be because the PATTERN, TARGET_NAMESPACE, COMPONENT, and SECRET variables are not defined in the industrial-edge Makefile. (I signed off on removing them, sorry!).

A better question might be whether this should delegate to common at all, or whether we should move this code purely into industrial edge. It will have to be modified in any case, I think

**Comment by mbaldessari** [comment]
Thanks Martin! 
I see three ways we can do this:
A) The 'export' trick way
So one way that seems quite non-intrusive could be just adding one line 'export' in the IE Makefile. That will make sure that the variables are passed down to the submake in common/Makefile.

So for example:
cat Makefile
```
FOO=bar
export
%:
        make -f common/Makefile $*
```
cat common/Makefile
```
test:
        echo $(FOO)
```

This will give us:
```
make test
make -f common/Makefile test
make[1]: Entering directory '/tmp/test'
echo bar
bar
make[1]: Leaving directory '/tmp/test'
```

If we override FOO inside the submake at common/Makefile that will take precedence.

B) We move argosecret target to IE
C) We revert the Makefile cleanup

I kinda like A) but need to think a bit more about it. I am unsure about B) because I do not know how generally useful this argocd will be.

**Comment by mhjacks** [comment]
I think that if we move the target from common to industrial edge (and the secret.sh script), it should work.

There are two reasons the pattern extracts the argocd admin secret:
1) To allow login as admin to the argocd UI. This is not needed anymore as we are using Dex/OIDC for that with kubeadmin.
2) To trigger the sync task in the build-and-test workflow. The pipeline fails with a nasty-looking error if it doesn't have the right secret to trigger that.

Of these, the first reason felt like the most important and general, and it has been mooted by Dex/OIDC. The second reason seems fairly particular to this workflow. When we were first developing the pattern there was some discussion over whether we should create a separate clusterrole/crb for the pipeline to do this; I was just learning the ropes of pipelines and a lot of other things, so it dropped in priority and we released without it. I think in the future if we have a similar workflow it would make sense to work out how to trigger argocd with a user dedicated to sync'ing as opposed to the cluster admin user. I don't know if the devsecops pattern is intending to do anything with this function or not - as a rule of thumb, I think, if we expect two patterns to need a piece of functionality it is a candidate to go into common (in keeping with the Don't Repeat Yourself principle). If it isn't, I'm not sure there's a pattern on the horizon or immediately beyond it that would need this.

That said, the approach this script and target uses is guaranteed to work as is, and there's no real harm in leaving the script in common. (It's not a data exposure of any kind, and patterns that don't need it are free not to use it.)

**Comment by mbaldessari** [comment]
Should be fixed via https://github.com/hybrid-cloud-patterns/common/pull/74  and https://github.com/hybrid-cloud-patterns/industrial-edge/pull/95

**Comment by mbaldessari** [comment]
I am going to close this one out as both PRs are merged. Let me know if we need to reopen
